# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---
# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".cache/**/*"
  - "coverage/**/*"
  - "public/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - ".gitignore"
  - "jest.config.js"

# Any typos we should ignore?
excluded_words:
  - typoci
  - "data-testid"

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
